-- 코드를 입력하세요
select  B.TITLE, B.BOARD_ID, R.REPLY_ID, R.WRITER_ID, R.CONTENTS,
TO_CHAR(R.CREATED_DATE,'YYYY-MM-DD') AS CREATED_DATE
from USED_GOODS_REPLY R,USED_GOODS_BOARD B
where B.BOARD_ID=R.BOARD_ID AND TO_CHAR(B.CREATED_DATE,'YYYY-MM')='2022-10'
ORDER BY R.CREATED_DATE ASC, B.TITLE ASC;